language: java
matrix:
  include:
    - jdk: oraclejdk7
      env: EAP_VERSION=6
    - jdk: oraclejdk8
      env: EAP_VERSION=6
    - jdk: oraclejdk8
      env: EAP_VERSION=7
addons:
  apt:
    packages:
      - oracle-java8-installer
before_script: 
  - sudo rm /etc/mavenrc
  - export MVN_OUTPUT=2
script:
  - ./build-eap$EAP_VERSION.sh
cache:
  directories:
  - $HOME/.m2
