language: java
matrix:
  include:
#    - jdk: openjdk7
#      env: EAP_VERSION=6
    - jdk: openjdk8
      env: EAP_VERSION=6
    - jdk: openjdk8
      env: EAP_VERSION=7
    - jdk: openjdk11
      env: EAP_VERSION=7
addons:
  apt:
    packages:
      - xmlstarlet
before_script: 
  - export MVN_OUTPUT=2
script:
  - ./build-eap$EAP_VERSION.sh
cache:
  directories:
  - $HOME/.m2
