FROM debian:bullseye as debian-jdk

ARG JDK_VERSION=11

RUN apt-get update && \
    apt-get install -y openjdk-$JDK_VERSION-jdk


# =====
FROM debian-jdk as eap-build

ARG EAP_VERSION

RUN apt-get install -y wget unzip patch curl maven xmlstarlet

WORKDIR eap-build-master
COPY . ./
RUN ./build-eap7.sh $EAP_VERSION && \
    unzip -q -d /opt dist/jboss-eap-*.zip && \
    mv /opt/jboss-eap-* /opt/jboss-eap


# =====
FROM debian-jdk

RUN groupadd -r jboss -g 1000 && \
    useradd -u 1000 -r -g jboss -m -d /opt/jboss-eap -s /sbin/nologin -c "JBoss user" jboss && \
    chmod 755 /opt/jboss-eap

COPY --from=eap-build --chown=jboss:0 /opt/jboss-eap /opt/jboss-eap
WORKDIR /opt/jboss-eap
USER jboss

EXPOSE 8080
EXPOSE 9990

CMD ["bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
