ARG JDK_VERSION=11
ARG JDK_IMAGE=azul/zulu-openjdk-alpine:$JDK_VERSION


# =====
FROM $JDK_IMAGE as eap-build

ARG EAP_VERSION

RUN apk update && \
    apk add bash wget unzip patch curl maven xmlstarlet

WORKDIR eap-build-master
COPY . ./
RUN ./build-eap7.sh $EAP_VERSION && \
    unzip -q -d /opt dist/jboss-eap-*.zip && \
    mv /opt/jboss-eap-* /opt/jboss-eap


# =====
FROM $JDK_IMAGE

RUN addgroup --gid 1000 jboss && \
    adduser -u 1000 -G jboss -h /opt/jboss-eap -D -s /sbin/nologin jboss && \
    chmod 755 /opt/jboss-eap

COPY --from=eap-build --chown=jboss:0 /opt/jboss-eap /opt/jboss-eap

WORKDIR /opt/jboss-eap
USER jboss
ENV LAUNCH_JBOSS_IN_BACKGROUND true

EXPOSE 8080
EXPOSE 9990

CMD ["bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
