versions=8.0.0,8.0.3

8.0.0.xpath.insert.core=common/src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml,/_:module/_:dependencies/_:module[position()=1],module,name="java.desktop"
8.0.0.xpath.delete.eap=ee-dist/pom.xml,//_:dependency[_:artifactId='wildfly-testsuite-shared']
8.0.3.xpath.insert.core=common/src/main/resources/modules/system/layers/base/org/jboss/as/domain-http-interface/main/module.xml,/_:module/_:dependencies/_:module[position()=1],module,name="java.desktop"
8.0.3.xpath.delete.eap=ee-dist/pom.xml,//_:dependency[_:artifactId='wildfly-testsuite-shared']
8.0.3.xpath.update.eap=pom.xml,//_:properties/_:version.org.wildfly.core,21.0.10.Final-redhat-00001
